# These are the default settings for this plugin, feel free to change the values to your needs
# Warning! Reloading the script / restarting the server will delete all active cool downs

# Scroll Of Teleportation

  # Level 1:

    # max distance in blocks that can be traveled (integer)
    # can be set to 0 to disable the distance restriction
        maxDistance: 2000

    # cool down in seconds before you can cast this spell again (integer)
    # minimum 8 seconds
        coolDown: 900

    # Allow interdimensional traveling, e.g. Nether -> End
    # This option disables the maxDistance when teleporting through worlds
        skipWorldCheck: false

  # Level 2:

    # max distance in blocks that can be traveled (integer)
    # can be set to 0 to disable the distance restriction
        maxDistance_lvl2: 10000

    # cool down in seconds before you can cast this spell again (integer)
    # minimum 8 seconds
        coolDown_lvl2: 1350 # Integer

    # Allow interdimensional traveling, e.g. Nether -> End
    # This option disables the maxDistance when teleporting through worlds
        skipWorldCheck_lvl2: false

  # Level 3:

    # max distance in blocks that can be traveled (integer)
    # can be set to 0 to disable the distance restriction
        maxDistance_lvl3: 0

    # cool down in seconds before you can cast this spell again (integer)
    # minimum 8 seconds
        coolDown_lvl3: 1800

    # Allow interdimensional traveling (boolean)
    # e.g. Nether -> End
        skipWorldCheck_lvl3: true
